spring.application.name=LinkTheFight
spring.datasource.url=jdbc:postgresql://localhost:5432/linkthefight
spring.datasource.username=admin
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.hibernate.ddl-auto=drop-and-create
spring.jpa.show-sql=true

# Clave de los tokens
jwt.secret=SuperSecretKey